sub-id = "your subscription id here"
resource_group_name = "RG6"
vnet_name           = "lab-vnet"
subnet_name         = "default-subnet"
vm_name             = "VM3"
admin_user          = "azureuser"
ssh_public_key_path = "~/.ssh/azure_automation_rsa.pub"
